# arch:
#     - arm64
#     - ppc64le

language: python

env:
  -CIBW_BEFORE_BUILD: pip install setuptools numpy

jobs:
  include:
    # ARMv8 Python 3.6 build
    - services: docker
      arch: arm64
      python: 3.6
      env: 
        -CIBW_BUILD: "cp36-*"
    # PPC64LE Python 3.6 build
    - services: docker
      arch: ppc64le
      python: 3.6
      env:
        - CIBW_BUILD: "cp36-*"
    # # PPC64LE Python 3.7 build
    # - services: docker
    #   arch: ppc64le
    #   python: 3.7
    #   env:
    #     - CIBW_BUILD: "cp37-*"
    # # PPC64LE Python 3.8 build
    # - services: docker
    #   arch: ppc64le
    #   python: 3.8
    #   env: 
    #     - CIBW_BUILD: "cp38-*"
    # # PPC64LE Python 3.9 build
    # - services: docker
    #   arch: ppc64le
    #   env: 
    #     - CIBW_BUILD: "cp39-*"


# python:
#   - 2.7
#   - 3.5
#   - 3.6
#   - 3.7
#   - 3.8
#   - 3.9

addons:
  artifacts:
    working_dir: wheelhouse

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  # - pip install numpy
  # - python -c "import numpy; print(numpy.__version__)"
  - which python
  # - which pip
  # - which python3
  # - which pip3
  - python -V

install:
  # - pip install .
  - pip install cibuildwheel==1.6.4

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse/
  # Run tests
  - mkdir empty
  - cd empty
  - python -c "import sys;import numexpr;sys.exit(0 if numexpr.test().wasSuccessful() else 1)"

