arch:
    - arm64
    - ppc64le

# jobs:
#   include:
#     # perform a linux ARMv8 build
#     - services: docker
#       arch: arm64
#     # perform a linux PPC64LE build
#     - services: docker
#       arch: ppc64le

language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -q numpy
  - python -V
  - pip install cibuildwheel==1.6.4

install:
  - pip install .

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
  # Run tests
  - mkdir empty
  - cd empty
  - python -c "import sys;import numexpr;sys.exit(0 if numexpr.test().wasSuccessful() else 1)"

