name: Build

on: [push, pull_request]

env:
  CIBW_BEFORE_BUILD: pip install setuptools oldest-supported-numpy
  CIBW_BUILD_VERBOSITY: 3
  # CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: python -c "import sys, numexpr; sys.exit(0 if numexpr.test().wasSuccessful() else 1)"
  CIBW_TEST_SKIP: "*macosx*arm64*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }} - ${{ matrix.cibw_build }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD: ${{ matrix.cibw_build }}
      CIBW_ARCHS_LINUX: ${{ matrix.arch }}
      CIBW_ARCHS_MACOS: ${{ matrix.arch }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64]
        cibw_build: ["cp3{6,7,8,9,10}-*"]
        include:
          - arch: arm64
            os: macos-latest
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "cp36*manylinux*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "cp37*manylinux*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "cp38*manylinux*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "cp39*manylinux*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "cp310*manylinux*"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU
      
      - name: Build wheels for Python
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      
      - name: Make sdist
        run: |
          python -m pip install build
          python -m build --sdist --outdir wheelhouse .

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheelhouse/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload wheelhouse/*
