name: Build

on: [push, pull_request]

env:
  CIBW_BEFORE_BUILD: pip install setuptools oldest-supported-numpy
  CIBW_BUILD_VERBOSITY: 3
  # CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: python -c "import sys, numexpr; sys.exit(0 if numexpr.test().wasSuccessful() else 1)"
  CIBW_TEST_SKIP: "*macosx*arm64*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD: ${{ matrix.cibw_build }}
      CIBW_ARCHS_LINUX: ${{ matrix.arch }}
      CIBW_ARCHS_MACOS: ${{ matrix.arch }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64]
        cibw_build: ["cp3{6,7,8,9,10}-*"]
        include:
          - arch: arm64
            os: macos-latest
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "*36*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "*37*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "*38*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "*39*"
          - arch: aarch64
            os: ubuntu-latest
            cibw_build: "*310*"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU
      
      - name: Build wheels for CPython
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
